### ISSUE TITLE
"Error. Can't read Ableton project" message: .als attached (Created with 9.2.2)

### ISSUE THREAD

**Issue by countachqv** [LucaTNT/als2cue_web#5]
Here it is an .als file that returns "Error. Can't read Ableton project" message.

This .als file was created with Ableton 9.2.2

Maybe this is caused because I'am using an old version?

[p143-mix_paula_01-v3.als.zip](https://github.com/LucaTNT/als2cue_web/files/8172878/p143-mix_paula_01-v3.als.zip)

**Comment by LucaTNT** [comment]
It appears to be a bug in the code that detects tempo changes, I'll try to have a look over the weekend.

**Comment by LucaTNT** [comment]
The bug was due to a different project format in Live 9.

I switched the parsing from my home-made library to @offlinemark's awesome [dawtool](https://github.com/offlinemark/dawtool) and now it works properly.

**Comment by countachqv** [comment]
Thanks ! 
BTW, https://als2cue.lucatnt.com/ is returning 404 right now, but www works fine. Something broke in the deploy?

**Comment by LucaTNT** [comment]
Yep, I had screwed it up. 
It should be working now.

**Comment by countachqv** [comment]
Tested and verified with other .als files. Works like a charm.

So, i've been making my cue and tracklist files manually, by looking at the time rule un ableton and typing the time and the marker name in a Notepad document like a retarded for [100+ sets](https://dj.juanprada.com). Go figure.

Cheers!
